version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: rechnungstool
      POSTGRES_USER: rechnungstool_user
      POSTGRES_PASSWORD: rechnungstool_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
